import { Library, LibraryItem } from "../store/library.interface.ts";

export const mockLibrary: Library = {
  MediaContainer: {
    size: 1,
    allowSync: true,
    title1: "Mock Title",
    Directory: [
      {
        allowSync: true,
        art: "/path/to/art",
        composite: "/path/to/composite",
        filters: true,
        refreshing: false,
        thumb: "/path/to/thumb",
        key: "mockKey",
        type: "artist",
        title: "Mock Title",
        agent: "Mock Agent",
        scanner: "Mock Scanner",
        language: "en",
        uuid: "mock-uuid",
        updatedAt: Date.now(),
        createdAt: Date.now(),
        scannedAt: Date.now(),
        content: true,
        directory: true,
        contentChangedAt: Date.now(),
        hidden: 0,
        Location: [
          {
            id: 1,
            path: "/path/to/location",
          },
        ],
      },
    ],
  },
};

export const mockLibraryItem: LibraryItem = {
  size: 1,
  totalSize: 1,
  offset: 0,
  allowSync: true,
  art: "/path/to/art",
  identifier: "mock-identifier",
  librarySectionID: 1,
  librarySectionTitle: "Mock Title",
  librarySectionUUID: "mock-uuid",
  mediaTagPrefix: "/path/to/mediaTag",
  mediaTagVersion: 1,
  nocache: false,
  thumb: "/path/to/thumb",
  title1: "Mock Title 1",
  title2: "Mock Title 2",
  viewGroup: "mock view group",
  viewMode: 1,
  Metadata: [
    {
      ratingKey: "mock-rating-key",
      key: "/path/to/key",
      parentRatingKey: "mock-parent-rating-key",
      guid: "mock-guid",
      parentGuid: "mock-parent-guid",
      studio: "Mock Studio",
      type: "mock-type",
      title: "Mock Title",
      parentKey: "/path/to/parentKey",
      parentTitle: "Mock Parent Title",
      index: 1,
      rating: 5,
      thumbBlurHash: "mock-thumb-blur-hash",
      year: 2022,
      thumb: "/path/to/thumb",
      art: "/path/to/art",
      parentThumb: "/path/to/parentThumb",
      originallyAvailableAt: "2022-01-01",
      addedAt: Date.now(),
      updatedAt: Date.now(),
      loudnessAnalysisVersion: "1.0.0",
      musicAnalysisVersion: "1.0.0",
      mediaCount: 1,
      mediaCountOptimized: 1,
      Genre: [
        {
          tag: "Mock Genre",
        },
      ],
    },
  ],
};
