import { PlexResource } from "../store/server.interface.ts";

export const mockPlexServerResource: PlexResource = {
  name: "Mock Server PlexResource",
  product: "Mock Product",
  productVersion: "Mock Version",
  platform: "Mock Platform",
  platformVersion: "Mock Platform Version",
  device: "Mock Server Device",
  clientIdentifier: "mock-client-identifier",
  createdAt: "2022-01-01T00:00:00Z",
  lastSeenAt: "2022-01-01T00:00:00Z",
  provides: "server",
  ownerId: "mock-owner-id",
  sourceTitle: "Mock Source Title",
  publicAddress: "mock-public-address",
  accessToken: "mock-access-token",
  owned: true,
  home: true,
  synced: true,
  relay: true,
  presence: true,
  httpsRequired: true,
  publicAddressMatches: true,
  dnsRebindingProtection: true,
  natLoopbackSupported: true,
  connections: [
    {
      protocol: "http",
      address: "localhost",
      port: 3000,
      uri: "http://localhost:5000",
      local: true,
      relay: false,
      IPv6: false,
    },
  ],
};

export const mockPlexClientResource: PlexResource = {
  name: "Mock Client PlexResource",
  product: "Mock Product",
  productVersion: "Mock Version",
  platform: "Mock Platform",
  platformVersion: "Mock Platform Version",
  device: "Mock Client",
  clientIdentifier: "mock-client-identifier",
  createdAt: "2022-01-01T00:00:00Z",
  lastSeenAt: "2022-01-01T00:00:00Z",
  provides: "client,player,pubsub-player",
  ownerId: "mock-owner-id",
  sourceTitle: "Mock Source Title",
  publicAddress: "mock-public-address",
  accessToken: "mock-access-token",
  owned: true,
  home: true,
  synced: true,
  relay: true,
  presence: true,
  httpsRequired: true,
  publicAddressMatches: true,
  dnsRebindingProtection: true,
  natLoopbackSupported: true,
  connections: [
    {
      protocol: "http",
      address: "localhost",
      port: 3000,
      uri: "http://localhost:3000",
      local: true,
      relay: false,
      IPv6: false,
    },
  ],
};

export const mockPlexResources = [mockPlexServerResource, mockPlexClientResource];
